name: 🚀 Deploy website on push
on:
    push:
        branches:
            - "production"
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: 🔨 Install Dependencies & Build
              run: |
                  npm ci
                  npm run build
                  cd dist/

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets.ftp_server }}
                  username: ${{ secrets.ftp_username }}
                  password: ${{ secrets.ftp_password }}
                  dangerous-clean-slate: false

            - name: ✅ Verify Deployment
              run: curl -Is https://yourdomain.com | head -n 1
